// @ts-check

/**
 * @description Membuat sidebar khusus parcel
 * @type {import("@docusaurus/plugin-content-docs").SidebarsConfig}
 */

const sidebar = {
  parcelSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebar;
